### PR TITLE
Added a complete flow for answering trivia questions

### PR DESCRIPTION
**Pull request by paco-mtz-design**
The flow is described in a very compact space, optimal for widgets or mobile display (with a few tweaks).

**Major changes to the Sketch file:**
- I noticed that this is a very specific category, so I added a new header to the Sketch file.
- Also added more descriptive names to each screen, I think this is important to provide better information about the specific function of each screen in the flow... I would like to set this as a standar in every other screens in the files, what do you think @scarlettgarza @Ramiro?
- Finally, I used letters (B, C, D) to extend a particular state and denote bifurcations in the flow (note it when the flow breaks between right and wrong answers in the trivia)

On a separate discussion, I would also like to propose that we use lower case for the screen naming; it's a bit more agile to type everything without worrying about case... for now, I tried to attach to the Sentence Case as much as I could (I'm pretty sure I might made a couple of mistakes in the names due to this so far 🙃)

### CODE REVIEW

**Comment by paco-mtz-design** [comment]
I'm sharing again the details for this PR, under a more thorough template for the request (next comment)

**Comment by paco-mtz-design** [comment]
### What does this PR do?

This PR adds a completely new flow, under the label of 'Trivia'. The flow is described in a very compact space, optimal for widgets or mobile display (with a few tweaks).

**Changes to the Sketch file:**

- Added a new header to the Sketch file.
- Added more descriptive names to each screen, I think this is important to provide better information about the specific function of each screen in the flow
- Added letter notation (B, C, D) to extend a particular state and denote bifurcations in the flow (note it when the flow breaks between right and wrong answers in the trivia)

**Files modified:**

- Flows/UI-Toolkit-Flows-V_0.1.sketch
- Artboards added: **11**
- Artboards edited: **0**
- Artboards deleted: **0**
- Edited in Sketch **v 50.2**

**Preview**

screen shot 2018-07-13 at 4 46 41 pm

**Review by scarlettgarza — CHANGES_REQUESTED** [review]
LGTM,

I already downloaded the sketch file and review it, everything looks fine, the only thing missing is the hover states for the answers/options.

**Comment by paco-mtz-design** [comment]
Thanks for the suggestion Scar, I modified the answers to be originally at 85% opacity,a nd become 100% opaque when hovered:

screen shot 2018-07-13 at 5 23 47 pm

**Review by scarlettgarza — APPROVED** [review]
Great, LGTM.

**Comment by paco-mtz-design** [comment]
This PR was succesfully merged with this commit:
https://github.com/IcaliaLabs/ux-toolkit/commit/27a1373052262e44fcf6394ee1a494f3d13d4cb3

**Pull request closed without merging**
